@startuml
'https://plantuml.com/sequence-diagram

class Square_Request{
super of ALL other Request classes.
}

class Catalog_Request {

}

class Catalog_Delete {
super
this._method: "POST"
this._endpoint: "/batch-delete"
this._body.object_ids: []
==
Simple Getters
==
Simple Setters
==
METHODS
==
+delete(id)
..
adds id to object_ids array

+effacer(id)
+nix(id)
+disintigrate(id)
 ..
 Aliases of delete()

==
MAKER METHODS
+ make()
==
}

class Catalog_Info {
super
this._method: "GET"
this._endpoint: "/info"
this._standard_unit_descriptions;
this._standard_unit_json = [];
this._language_code;
this._limits;
==
Simple Getters
==
Simple Setters
==
Complex Setters (Computed Properties)

+ delivery()
..
Checks for presence of standard units
Adds them to their own array if present
Sets other properties as well.

==
Private METHODS
#convertToJson()
...
Stringifies standard unit description in Response

==
==
MAKER METHODS
+ make()
==
}


class Catalog_List {
super : Catalog_Request
this._method: "GET"
this._endpoint: "/list"
this._fardel
fardel.catalog_version
this._delivery
==
Simple Getters
==
Simple Setters
==
Complex Setters (Computed Properties)

+types(str)
..
concatenates types into a CSV list
==
Private METHODS
+#enum_types()
==
==
MAKER METHODS
+ make()
==
}

class Catalog_Retrieve {
super: Catalog_Request
this._method: "POST"
this._endpoint
this._body
==
Simple Getters
==
Simple Setters
==
Complex Setters (Computed Properties)
==
Private METHODS

+#enum_()
...
set respective properties with FIXED values

==
==
MAKER METHODS
+ make()
==
}


class Catalog_Search_Objects_Super {
super
this._method: "POST"
this._endpoint
this._body
==
Simple Getters
==
Simple Setters
==
Complex Setters (Computed Properties)
==
Private METHODS

+#enum_()
...
set respective properties with FIXED values

==
==
MAKER METHODS
+ make()
==
}

class Catalog_Search_Cross_Reference{
super
this._method: "POST"
this._endpoint
this._body
==
Simple Getters
==
Simple Setters
==
Complex Setters (Computed Properties)
==
Private METHODS

+#enum_()
...
set respective properties with FIXED values

==
==
MAKER METHODS
+ make()
==
}


class Catalog_Search_Filter{
super
this._method: "POST"
this._endpoint
this._body
==
Simple Getters
==
Simple Setters
==
Complex Setters (Computed Properties)
==
Private METHODS

+#enum_()
...
set respective properties with FIXED values

==
==
MAKER METHODS
+ make()
==
}




class Catalog_Search_Items{
super
this._method: "POST"
this._endpoint
this._body
this._attribute_filter
==
Simple Getters
==
Simple Setters
==
Complex Setters (Computed Properties)
==
Private METHODS
+#init_filter()
...
initializes this._attribute_filter

+#enum_sort_order()
+#enum_product_type()
+#enum_stock_levels()
...
set respective properties with FIXED values

==
==
MAKER METHODS
+ make()
+ make_custom_attribute_filter()
==
}



class Catalog_Upsert {
super
this._method: "POST"
this._endpoint
this._body
==
Simple Getters
==
Simple Setters
==
Complex Setters (Computed Properties)
==
Private METHODS

+#enum_()
...
set respective properties with FIXED values

==
==
MAKER METHODS
+ make()
==
}





@enduml