@startuml
'https://plantuml.com/class-diagram

Square_Request <-- Invoice_Request
Invoice_Request <-- Invoice_RUDCnP
Invoice_Request <-- Invoice_Create
Invoice_Request <-- Invoice_List
Invoice_Request <-- Invoice_Search
Invoice_RUDCnP <- Invoice_Cancel
Invoice_RUDCnP <- Invoice_Delete
Invoice_RUDCnP <- Invoice_Publish
Invoice_RUDCnP <- Invoice_Retrieve
Invoice_RUDCnP <- Invoice_Update

abstract class Square_Request{
super of ALL other Request classes.
}

abstract class Invoice_Request {
super: Square_Request
_display_name
this._api_name: "invoice"
this._delivery
}

abstract class Invoice_RUDCnP {
constructor(id)
super: Invoice_Request
_display_name
this._endpoint = `/${id}`
==
MAKER METHODS

+make()
==
}


class Invoice_Create {
constructor(id)
super: Invoice_Request
_display_name
_last_verified_square_api_version
_help
this._method: "POST"
this._endpoint = ""
this._body
_body.invoice
_body.idempotency_key

this.configuration
==
Getters
==
Setters
==
MAKER METHODS

+make()
==
Square Docs
[[https://developer.squareup.com/reference/square/invoices-api/create-invoice Invoice_Create ]]
}


class Invoice_List {
constructor(location_id)
super: Invoice_Request
_display_name
_last_verified_square_api_version
_help
this._method: "GET"
this._endpoint = QUERY PARAMS
this._delivery = []
this._body
_body.version
_body.idempotency_key
this.configuration
==
Getters
==
Setters
==
MAKER METHODS

+make()
==
Square Docs
[[https://developer.squareup.com/reference/square/invoices-api/list-invoices Invoice_List ]]
}



class Invoice_Cancel {
constructor(id)
super: Invoice_RUDCnP
_display_name
_last_verified_square_api_version
_help
this._method: "POST"
this._endpoint = `/${id}/cancel`
this._body
_body.version

==
Getters
==
Setters
==
MAKER METHODS

+make()
==
Square Docs
[[https://developer.squareup.com/reference/square/invoices-api/cancel-invoice Invoice_Cancel ]]
}


class Invoice_Delete {
constructor(id)
super: Invoice_RUDCnP
_display_name
_last_verified_square_api_version
_help
this._method: "POST"
this._method = "DELETE"
this._delivery
==
Getters
==
Setters
==
Square Docs
[[https://developer.squareup.com/reference/square/invoices-api/delete-invoice Invoice_Delete ]]
}

class Invoice_Publish {
constructor(id)
super: Invoice_RUDCnP
_display_name
_last_verified_square_api_version
_help
this._method: "POST"
this._endpoint = `/${id}/publish`
this._body
_body.version
_body.idempotency_key
this.configuration
==
Getters
==
Setters
==
MAKER METHODS

+make()
==
Square Docs
[[https://developer.squareup.com/reference/square/invoices-api/publish-invoice Invoice_Publish ]]
}


class Invoice_Retrieve {
constructor(id)
super: Invoice_RUDCnP
_display_name
_last_verified_square_api_version
_help
this._method: "GET"

==
Getters
==
Square Docs
[[https://developer.squareup.com/reference/square/invoices-api/get-invoice Invoice_Retrieve ]]
}

class Invoice_Search {
constructor(id)
super: Invoice_Request
_display_name
_last_verified_square_api_version
_help
this._method: "POST"
this._endpoint = "/search"
this._body
_body.query: {filter, sort}
_body.limit
_body.cursor
this.configuration
==
Getters
==
Setters
==
Private Methods
==
+#sort_order()
+#build_query()
==
MAKER METHODS

+make()
==
Square Docs
[[https://developer.squareup.com/reference/square/invoices-api/search-invoices Invoice_Search ]]
}

class Invoice_Update {
constructor(invoice_document)
super: Invoice_RUDCnP
_display_name
_last_verified_square_api_version
_help
_reason - (validation failure)
this._method: "PUT"
this._square_invoice_document
this._invoice_is_updatable
this._invoice_is_published

this._body
_body.idempotency_key
_body.invoice
_body.fields_to_clear

this.configuration
==
Getters
==
Setters
==
Private Methods
+#is_invoice_published()
+#is_updatable()
+#compare_version(fardel)
+#validate_primary_recipient(fardel)
+#validate_order_id(fardel)
+#validate_location_id(fardel)
+#can_clear_primary_recipient()
==
Public Methods
+validate(fardel = this._body.invoice)
==
MAKER Methods
+make()
==
Square Docs
[[https://developer.squareup.com/reference/square/invoices-api/update-invoice Invoice_Update ]]
}






@enduml