@startuml
'https://plantuml.com/class-diagram


Square_Request <-- Order_Request
Order_Request <- Order_Calculate
Order_Request <- Order_Create
Order_Request <- Order_Clone
Order_Request <- Order_Pay
Order_Request <- Order_Retrieve
Order_Request <- Order_Search
Order_Request <- Order_Update


abstract class Square_Request{
super of ALL other Request classes.
}

abstract class Order_Request {
super: Square_Request
this._api_name: "order"
}


class Order_Calculate {
super: Order_Request
_display_name
_last_verified_square_api_version
this._method: ""
this._endpoint: ""
this._body

==
Getters
==
Setters
==
MAKER METHODS

+make()
==
Square Docs
[[ Order_ ]]
}

class Order_Create  {
super: Order_Request
_display_name
_last_verified_square_api_version
this._method: ""
this._endpoint: ""
this._body

==
Getters
==
Setters
==
MAKER METHODS

+make()
==
Square Docs
[[ Order_ ]]
}
class Order_Clone  {
super: Order_Request
_display_name
_last_verified_square_api_version
this._method: ""
this._endpoint: ""
this._body

==
Getters
==
Setters
==
MAKER METHODS

+make()
==
Square Docs
[[ Order_ ]]
}
class Order_Pay  {
super: Order_Request
_display_name
_last_verified_square_api_version
this._method: ""
this._endpoint: ""
this._body

==
Getters
==
Setters
==
MAKER METHODS

+make()
==
Square Docs
[[ Order_ ]]
}
class Order_Retrieve  {
super: Order_Request
_display_name
_last_verified_square_api_version
this._method: ""
this._endpoint: ""
this._body

==
Getters
==
Setters
==
MAKER METHODS

+make()
==
Square Docs
[[ Order_ ]]
}
class Order_Search  {
super: Order_Request
_display_name
_last_verified_square_api_version
this._method: ""
this._endpoint: ""
this._body

==
Getters
==
Setters
==
MAKER METHODS

+make()
==
Square Docs
[[ Order_ ]]
}
class Order_Update {
super: Order_Request
_display_name
_last_verified_square_api_version
this._method: ""
this._endpoint: ""
this._body

==
Getters
==
Setters
==
MAKER METHODS

+make()
==
Square Docs
[[ Order_ ]]
}


@enduml